---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJpbnRlcm5hbC1kZXZlbG9wbWVudC1kb2NrZXItY29tbW9uLnBzbWFuYWdlZC5jb20iOnsidXNlcm5hbWUiOiJuZXh1cy1kZXYtZG9ja2VyIiwicGFzc3dvcmQiOiJDd1h4PUJYVUNMU1AtNkdRIiwiYXV0aCI6ImJtVjRkWE10WkdWMkxXUnZZMnRsY2pwRGQxaDRQVUpZVlVOTVUxQXROa2RSIn19fQ==
kind: Secret
metadata:
  name: common-registry-secret
type: kubernetes.io/dockerconfigjson
